### ISSUE TITLE
RDS file 

### ISSUE THREAD

**Issue by ktrns** [MHH-RCUG/scrnaseq_app#21]
Hi again, 

At what point are you guys creating the RDS file? 

In my original code, I am saving an RData image. I should probably adapt that, so our clients can use this app. 

Best and thanks
Katrin

**Comment by mariusrueve** [comment]
Already solved through slack, pasting answer for documentation:

I have added a line with `saveRDS(...)` to the end of your script (below/ instead of the creation of the .RData file) to create the .rds file.
Save and readRDS() is part of the base package and is used in the [Seurat workflow](https://satijalab.org/seurat/v3.2/pbmc3k_tutorial.html).
