### ISSUE TITLE
subscript out of bounds during gene selection

### ISSUE THREAD

**Issue by dimialex** [MHH-RCUG/scrnaseq_app#28]
Hi again,
is there a maximum number of genes to be selected? After loading the 7th gene of interest (LINC01342), I get the following error:
<pre>
Warning: Error in [[: subscript out of bounds
  174: strsplit
  167: renderPlot [/scrnaseq_app_test/scrnaseq_app-0.0.1/scrnaseq_app.R#232]
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$plot_feature2
    1: runApp
Warning: Could not find LINC01342 in the default search locations, found in RNA assay instead
Warning: Could not find LINC01342 in the default search locations, found in RNA assay instead
Warning: Could not find LINC01342 in the default search locations, found in RNA assay instead
Warning: Could not find LINC01342 in the default search locations, found in RNA assay instead
</pre>

I am using the current initial release, but now see there were 13 commits to master since this release.
Best,
Dimitra

**Comment by mariusrueve** [comment]
I've tested this with 16 selected genes and it didn't crash. I only got the message `Warning: Could not find AC105942.1 in the default search locations, found in RNA assay instead` several times, but after a while, when everything was plotted it stopped.

I've made some changes to the creation and storage of the plots. Maybe that's why it didn't crash for me.
